branches:
  only:
    - master

language: node_js

# https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements
# @ To compile native modules
env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
# To compile native modules @

install:
  - npm install

before_script:
  # @ open FireFox
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # open FireFox @

script:
  - npm test
  - npm run build
  - npm run gen:html
  - npm run server & # run a command in the background by appending '&'
  - sleep 3 # give a server some time to start
  - npm run e2e:ff
