branches:
  only:
    - master

language: node_js

# https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements
# @ To compile native modules
env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
# To compile native modules @
  # the latest version(v47) emits Error: Timed out waiting for the WebDriver server at http://127.0.0.1:47624/hub
  # firefox: "latest" # default 31.0
  firefox: "46.0"

install:
  - npm install

before_script:
  # @ open FireFox
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # open FireFox @

script:
  - npm test
  - npm run build
  - npm run gen:html
  - npm run server & # run a command in the background by appending '&'
  - sleep 3 # give a server some time to start
  - npm run e2e:ff

after_success:
  # because of this issue, https://github.com/marcules/karma-remap-istanbul/issues/3
  # use remap-istanbul to generate 'lcov.info' from 'coverage-final.json'
  - cat ./coverage/coverage-final.json | ./node_modules/.bin/remap-istanbul -o ./coverage/lcov.info -t lcovonly
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
