# https://www.appveyor.com/docs/appveyor-yml
# http://www.appveyor.com/docs/lang/nodejs-iojs

skip_commits:
  message: /\[skip appveyor\]/

branches:
  only:
  - master

# https://www.appveyor.com/blog/2014/06/04/shallow-clone-for-git-repositories
clone_depth: 10

# https://www.appveyor.com/docs/build-cache
cache: node_modules

environment:
  nodejs_version: "6.2.1"

# Install scripts. (runs after repo cloning)
install:
  - ps: Install-Product node $env:nodejs_version # ps: => PowerShell, cmd: cmd
  - del .\npm-shrinkwrap.json
  # - ren .\npm-shrinkwrap.window.json npm-shrinkwrap.json
  - npm install

# MSBUILD off
build: off

# Post-install test scripts.
test_script:
  - npm run test:ie
  - npm run build
  - npm run gen:html
  - npm run e2e:one:ie
