# http://www.appveyor.com/docs/lang/nodejs-iojs

skip_commits:
  message: /\[skip appveyor\]/

branches:
  only:
  - master

environment:
  nodejs_version: "6.2.1"

# Install scripts. (runs after repo cloning)
install:
  - ps: Install-Product node $env:nodejs_version # ps => PowerShell
  - del .\npm-shrinkwrap.json
  - npm install

build: off

# Post-install test scripts.
test_script:
  - npm run test:ie
  - npm run build
  - npm run gen:html
  - START /B npm run server # run a command in the background
  - timeout 3 # give a server some time to start
  - npm run e2e:ie
