# https://www.appveyor.com/docs/appveyor-yml
# http://www.appveyor.com/docs/lang/nodejs-iojs

skip_commits:
  message: /\[skip appveyor\]/

branches:
  only:
  - master

services:
  - iis

environment:
  nodejs_version: "6.2.1"

# Install scripts. (runs after repo cloning)
install:
  - ps: Install-Product node $env:nodejs_version # ps: => PowerShell, cmd: cmd
  - del .\npm-shrinkwrap.json
  - npm install

# MSBUILD off
build: off

# Post-install test scripts.
test_script:
  - npm run test:ie
  - npm run build
  - npm run gen:html
  - echo %cd%
  # - npm run server & ls & npm run e2e:ie # run a command in a new CMD
  # - timeout 3 # give a server some time to start
  # - sleep 3
  # - npm run e2e:ie

deploy:
  - provider: Local
    # port: 8080
    # path: .\dist
  narr-app.deploy_website: true
  narr-app.site_name: Test
  narr-app.hostname: localhost
  narr-app.port: 8080
  narr-app.protocol: http
  narr-app.path: .\dist

after_deploy:
  - npm run e2e:ie
